### ISSUE TITLE
Summary/Short Mode

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/cloud-cost-reporter#72]
While the current daily messages contain a lot of useful data, akin to "showing the working" for the various costs, a way of producing a digest of daily costs can come in useful for quick-glance understanding of costs.

I propose that this message would only contain:
```
:moneybag: Usage for DATE :moneybag:
Compute Costs (USD): X
Data Out Costs (USD): X
Total Costs(USD): X
Total Compute Units (Flat): X
Total Compute Units (Risk): X
FC Credits: X
```

Question: Would this be better as a CLI flag or a per-project setting?

**Comment by timalces** [comment]
Regarding CLI flag vs per-project setting, either is reasonably straightforward technically, so I guess it depends if:

- you envisage having your daily cron always using this/ the same version for all projects (either suitable: can add this flag to cron job or as a default project setting)
- you envisage having your daily cron using this version for some projects and existing version for others (project setting more suitable)
- this / the existing version is just for other ad hoc running (flag more suitable, as otherwise involves manually changing project settings back and forth)

And if a combination of the above, could have both, with the flag overriding the project specific setting.

**Comment by timalces** [comment]
@ColonelPanicks what are your thoughts on the above?

**Comment by ColonelPanicks** [comment]
Oops, I'd read this response and not gotten back to it, ta for the prod.

I think it's more likely to be something at a CLI level than at a project level (as it's relating to the general output of the tool) so I'd be happy to have it as a CLI flag. A per-project basis is probably too much fine-tuning so we can ignore that for now.
